[build]
command = "npm start"  # Changed from "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"  # Changed from "/" to "/*" to catch all routes
to = "/index.html"
status = 200
force = true

[dev]
framework = "vite"